
# Notification Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: 986778210363.dkr.ecr.us-west-2.amazonaws.com/accounts:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: microservices-db-credentials
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: microservices-db-credentials
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: microservices-db-credentials
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: microservices-db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservices-db-credentials
                  key: DB_PASSWORD
            - name: DB_SSLMODE
              valueFrom:
                secretKeyRef:
                  name: microservices-db-credentials
                  key: DB_SSLMODE
            - name: DB_SSLROOTCERT
              valueFrom:
                secretKeyRef:
                  name: microservices-db-credentials
                  key: DB_SSLROOTCERT
          volumeMounts:
            - name: rds-cert
              mountPath: /certs
      volumes:
        - name: rds-cert
          hostPath:
            path: /certs
            type: Directory

---
